package com.example.model

data class ClickTarget(
    val id: Long = 0,
    val scriptId: Long = 0,
    val order: Int = 1,
    val type: TargetType = TargetType.SINGLE_TAP,
    val xPx: Float = 500f,
    val yPx: Float = 1000f,
    val swipeEndXPx: Float = 500f,
    val swipeEndYPx: Float = 500f,
    val delayMs: Long = 500L,
    val durationMs: Long = 100L,
    val label: String = "Target 1",
    val sizePx: Float = 96f,
    val isLocked: Boolean = false,
    val textContent: String = "",
    val mediaUri: String = "",
    val repeatCount: Int = 1,
    val minUnreadCount: Int = 1,
    val processOrder: String = UnreadChatSettings.ORDER_TOP_TO_BOTTOM,
    val maxChatsToOpen: Int = 0,
    val skipPinnedChats: Boolean = false,
    val skipMutedChats: Boolean = false,
    val autoScroll: Boolean = true,
    val stopAtEnd: Boolean = true,
    val excelFilePath: String = "",
    val excelRulesContent: String = "",
    val matchThreshold: Float = 0.3f,
    val fallbackReply: String = "",
    val voiceToTextDelayBeforeMs: Long = 1000L,
    val voiceToTextWaitAfterMs: Long = 1000L,
    val voiceToTextRetryCount: Int = 5,
    val voiceToTextRetryIntervalMs: Long = 500L,
    val voiceToTextSearchTimeoutMs: Long = 3000L,
    val aiIntentApiKey: String = ""
)
